import random

pkmons = ["Bulbasaur","Ivysaur","Venusaur","Charmander","Charmeleon","Charizard","Squirtle","Wartortle","Blastoise",
          "Caterpie","Metapod","Butterfree","Weedle","Kakuna","Beedrill","Pidgey","Pidgeotto","Pidgeot","Rattata",
          "Raticate","Spearow","Fearow","Ekans","Arbok","Pikachu","Raticate","Sandwhrew","Sandslash","Nidoran(♀)",
          "Nidorina","Nidoqueen","Nidoran(♂)","Nidorino","Nidoking","Clefairy","Clefable","Vulpix","Ninetales",
          "Jigglypuff","Wigglytuff","Zubat","Golbat","Oddish","Gloom","Vileplume","Paras","Parasect","Venonat",
          "Venomoth","Diglett","Dugtrio","Meowth","Persian","Psyduck","Golduck","Mankey","Primeape","Growlithe",
          "Arcanine","Poliwag","Poliwhirl","Poliwrath","Abra","Kadabra","Alakazam","Machop","Machoke","Machamp",
          "Bellsprout","Weepinbell","Victreebel","Tentacool","Tentacruel","Geodude","Graveler","Golem","Ponyta",
          "Rapidash","Slowpoke","Slowbro","Magnemite","Magneton","Farfetch'd","Doduo","Dodrio","Seel","Dewgong",
          "Grimer","Muk","Shellder","Cloyster","Gastly","Haunter","Gengar","Onix","Drowzee","Hypno","Krabby","Kingler",
          "Voltorb","Electrode","Exeggcute","Exeggutor","Cubone","Marowak","Hitmonlee","Hitmonchan","Lickitung",
          "Koffing","Weezing","Rhyhorn","Rhydon","Chansey","Tangela","Kangastan","Horsea","Seadra","Goldeen","Seaking",
          "Staryu","Starmie","Mr. Mime","Scyther","Jynx","Electabuzz","Magmar","Pinsir","Tauros","Magikarp","Gyarados",
          "Lapras","Ditto","Eevee","Vaporeon","Jolteon","Flareon","Porygon","Omanyte","Omastar","Kabuto","Kabutops",
          "Aerodactyl","Snorlax","Articuno","Zapdos","Moltres","Dratini","Dragonair","Dragonite","Mewtwo","Mew",

          "Chikorita","Bayleef","Meganium","Cyndaquil","Quilava","Typhlosion","Totodile","Croconaw","Feraligatr",
          "Sentret","Furret","Hoothoot","Noctowl","Ledyba","Ledian","Spinarak","Ariados","Crobat","Chinchou","Lanturn",
          "Pichu","Cleffa","Igglybuff","Togepi","Togetic","Natu","Xatu","Mareep","Flaaffy","Ampharos","Bellossom",
          "Marill","Azumarill","Sudowoodo","Politoed","Hoppip","Skiploom","Jumpluff","Aipom","Sunkern","Sunflora",
          "Yanma","Wooper","Quagsire","Espeon","Umbreon","Murkrow","Slowking","Misdreavus","Unown","Wobbuffet",
          "Girafarig","Pineco","Forretress","Dunsparce","Gligar","Steelix","Snubbull","Granbull","Qwilfish","Scizor",
          "Shuckle","Heracross","Sneasel","Teddiursa","Ursaring","Slugma","Magcargo","Swinub","Piloswine","Corsola",
          "Remoraid","Octilery","Delibird","Mantine","Sharkmory","Houndour","Houndoom","Kingdra","Phanpy","Donphan",
          "Porygon2","Stantler","Smeargle","Tylogue","Hitmontop","Smoochum","Elekid","Magby","Miltank","Blissey",
          "Raikou","Entei","Suicune","Larvitar","Pupitar","Tyranitar","Lugia","Ho-Oh","Celebi",

          "Treecko","Grovyle","Sceptile","Torchic","Combusken","Blaziken","Mudkip","Marshtomp","Swampert","Poochyena",
          "Mightyena","Zigzagoon","Linoone","Wurmple","Silcoon","Beautify","Cascoon","Dustox","Lotad","Lombre",
          "Ludicolo","Seedot","Nuzleaf","Shiftry","Taillow","Swellow","Wingul","Peliper","Ralts","Kirlia","Gardevoir",
          "Surskit","Masquerain","Shroomish","Breelom","Slakoth","Vigoroth","Slaking","Nincada","Ninjask","Shedinja",
          "Whismur","Loudread","Exploud","Makuhita","Hariyama","Azurill","Nosepass","Skitty","Delcatty","Sableye",
          "Mawile","Aron","Lairon","Aggron","Meditite","Medicaham","Electrike","Manectric","Plusle","Minun","Volbeat",
          "Illumise","Roselia","Gulpin","Swalot","Carvanha","Sharpedo","Wailmer","Wailord","Numel","Camerupt","Torkoal",
          "Spoink","Grumpig","Spinda","Trapinch","Vibrava","Flygon","Cacnea","Cactune","Swablu","Altaria","Zangoose",
          "Seviper","Lunatone","Solrock","Barboach","Whiscash","Corphish","Crawdaunt","Baltoy","Claydol","Lileep",
          "Cradily","Anorith","Armaldo","Feebas","Milotic","Castform","Kecleon","Shuppet","Banette","Duskull",
          "Dusclops","Tropius","Chimecho","Absol","Wynaut","Snorunt","Glalie","Spheal","Sealeo","Walrein","Campearl",
          "Huntail","Gorebyss","Relicanth","Luvdisc","Bagon","Shelgon","Salamence","Beldum","Metang","Metagross",
          "Regirock","Regice","Registeel","Latias","Latios","Kyogre","Groudon","Rayquaza","Jirachi","Deoxys",

          "Turtwig","Grotle","Torterra","Chimchar","Monferno","Infernape","Piplup","Prinplup","Empoleon","Starly",
          "Staravia","Staraptor","Bidoof","Bibarel","Kricketot","Kricketune","Shinx","Luxio","Luxray","Budew",
          "Roserade","Cranidos","Rampardos","Shieldon","Bastiodon","Burmy","Wormadam","Mothim","Combee","Vespiquen",
          "Pachirisu","Buizel","Floatzel","Cherubi","Cherrim","Shellos","Gastrodon","Ambipom","Drifloon","Drifblim",
          "Buneary","Lopunny","Mismagius","Honchkrow","Glameow","Purugly","Chingling","Stunky","Skuntank","Bronzor",
          "Bronzong","Bonsly","Mime Jr.","Happiny","Chatot","Spiritomb","Gible","Gabite","Garchomp","Munchlax","Riolu",
          "Lucario","Hippopotas","Hippowdon","Skorupi","Drapion","Croagunk","Toxicroak","Carnivine","Finneon",
          "Lumineon","Mantyke","Snover","Abomasnow","Weavile","Magnezone","Lickilicky","Rhyperior","Tangrowth",
          "Electivire","Magmortar","Togekiss","Yanmega","Leafeon","Glaceon","Gliscor","Mamoswine","Porygon-Z","Gallade",
          "Probopass","Dusknoir","Froslass","Rotom","Uxie","Mesprit","Azelf","Dialga","Palkia","Heatran","Regigigas",
          "Giratina","Cresselia","Phione","Manaphy","Darkrai","Shaymin","Arceus",

          "Victini","Snivy","Servine","Serperior","Tepig","Pignite","Emboar","Oshawott","Dewott","Samurott","Patrat",
          "Watchog","Lillipup","Herdier","Stoutland","Purrloin","Liepard","Pansage","Simisage","Pansear","Simisear",
          "Panpour","Simipour","Munna","Musharna","Pidove","Tranquill","Unfezant","Blitzle","Zebstrika","Roggenrola",
          "Boldore","Gigalith","Woobat","Swoobat","Drilbur","Excadrill","Audino","Timburr","Gurdurr","Conkeldurr",
          "Tympole","Palpitoad","Saismitoad","Throh","Sawk","Sewaddle","Swadloon","Leavanny","Vanipede","Scolipede",
          "Cottonee","Whimsicott","Petilil","Basculin","Sandile","Krokorok","Krookodile","Darumaka","Darmanitan",
          "Maractus","Dwebble","Crustle","Scraggy","Sigilyph","Yamask","Cofagrigus","Tirtouga","Carracosta","Archen",
          "Archeops","Trubbish","Garbodor","Zorua","Zoroark","Minccino","Cinccino","Gothita","Gothorita","Gothitelle",
          "Solosis","Duosion","Reuniclus","Ducklett","Swanna","Vanillite","Vanillish","Vanilluxe","Deerling","Sawsbuck",
          "Emolga","Karrablast","Escavalier","Foongus","Amoonguss","Frillish","Jellicent","Alomomola","Joltik",
          "Galvantula","Ferroseed","Ferrothorn","Klink","Klang","Klinglang","Tynamo","Eelektrik","Eelektross","Elgyem",
          "Beheeyem","Litwick","Lampent","Chandelure","Axew","Fraxure","Haxorus","Cubchoo","Beartic","Cryogonal",
          "Shelmet","Accelgor","Stunfisk","Mienfoo","Mienshao","Druddigon","Golett","Golurk","Pawniard","Bisharp",
          "Bouffalant","Rufflet","Breviary","Vullaby","Mandibuzz","Heatmor","Durant","Deino","Zweilous","Hydreigon",
          "Larvesta","Volcarona","Cobalion","Terrakion","Virizion","Tornadus","Thundurus","Reshiram","Zekrom",
          "Landorus","Kyurem","Kaldeo","Meloetta","Genesect",

          "Chespin","Quilladin","Chesnaught","Fennekin","Braixen","Delphox","Froakie","Frogadier","Greninja","Bunnelby",
          "Diggersby","Fletchling","Fletchinder","Talonflame","Scatterbug","Spewpa","Vivillon","Litleo","Pyroar",
          "Flabébé","Floette","Florges","Skiddo","Gogoat","Pancham","Pangoro","Furfrou","Espurr","Meowstic","Honedge",
          "Doublade","Aegislash","Spiritzee","Aromatisse","Swirlix","Slurpuff","Inkay","Malamar","Binacle","Barbaracle",
          "Skrelp","Dragalge","Claucher","Clawitzer","Helioptile","Heliolisk","Tyrunt","Tyrantrum","Amaura","Aurorus",
          "Sylveon","Hawlucha","Dedenne","Carbink","Goomy","Sliggo","Goodra","Klefki","Phantump","Trevenant",
          "Pumpkabbo","Gourgeist","Bergmite","Avalugg","Noibat","Noivern","Xerneas","Yveltal","Zygarde","Diancie",
          "Hoopa","Volcanion",

          "Rowlet","Dartrix","Decidueuye","Litten","Torracat","Incineroar","Popplio","Brionne","Prismarina","Pipikek",
          "Trumbeak","Toucannon","Yungoos","Gumshoos","Grubbin","Charjabug","Vikavolt","Crabrawler","Crabominable",
          "Oricorio","Cutiefly","Ribombee","Rockruff","Lycanroc","Wishicashi","Marenie","Toxapex","Mudbray","Mudscale",
          "Dewpider","Araquanid","Formantis","Lurantis","Morelull","Shiinotic","Salandit","Salazzle","Stufful","Bewear",
          "Bounsweet","Steenee","Tsareena","Comfey","Oranguru","Passimian","Wimpod","Golisopod","Sandygast","Palossand",
          "Pyukumuku","Type: Null","Silvally","Minior","Komala","Turtonator","Togedemaru","Mimikyu","Bruxish","Drampa",
          "Dhelmise","Jangmo-o","Hakamo-o","Kommo-o","Tapu Koko","Tapu Lele","Tapu Bulu","Tapu Fini","Cosmog","Cosmoem",
          "Solgaleo","Lunala","Nihilego","Buzzwole","Pheromosa","Xurkitree","Celesteela","Kartana","Guzzlord",
          "Necrozma","Magaerna","Marshadow","Poipole","Naganadel","Stakataka","Blacephalon","Zeraora","Melan",
          "Melmetal","Alolan Rattata","Alolan Ricate","Alolan Raichu","Alolan Sandshrew","Alolan Sandslash",
          "Alolan Vulpix","Alolan Ninetales","Alolan Diglett","Alolan Dugtrio","Alolan Meowth","Alolan Persian",
          "Alolan Geodude","Alolan Graveler","Alolan Golem","Alolan Grimer","Alolan Muk","Alolan Exeggutor"
         ,"Alolan Marowak",

          "Grookey","Thwackey","Rillaboom","Scorbunny","Raboot","Cinderace","Sobble","Drizzile","Inteleon","Skwovet",
          "Greedent","Rookidee","Corvisquire","Corviknight","Blipbug","Dottler","Orbeetie","Nickit","Thievul",
          "Gossifleur","Eldegoss","Wooloo","Dubwool","Chewtle","Drednaw","Yamper","Boltund","Rolycoly","Carkol",
          "Coalossal","Applin","Flapple","Appletun","Silicobra","Sandraconda","Cramorant","Arrokuda","Barraskewda",
          "Toxel","Toxtricity","Sizzilipede","Centiskorch","Clobbopus","Grapploct","Sinistea","Polteageist","Hatenna",
          "Hattrem","Hatterene","Impidimp","Morgrem","Grimmsnarl","Obstagoon","Perrserker","Cursola","Sirfetch'd",
          "Mr.Rime","Ronerigus","Milcery","Alcremie","Falinks","Pincurchin","Snom","Frosmoth","Stonjourner","Eiscue",
          "Indeedee","Morpeko","Cufant","Copperrajah","Dracozolt","Arctozolt","Dracovish","Arctovish","Duraludon",
          "Dreepy","Drakloak","Dragapult","Zacian","Zamazenta","Eternatus","Kubfu","Urshifu","Zarude","Regieleki",
          "Regidrago","Glastrier","Spectrier","Calyrex","Calyrex mounting on Glastrier","Calirex mounting on Spectrier",
          "Galarian Meowth","Galarian Ponyta","Galarian Rapidash","Galarian Slowpoke","Galarian Slowbro",
          "Galarian Farfetch'd","Galarian Weezing","Galarian Mr. Mine","Galarian Articuno","Galarian Zapdos",
          "Galarian Moltres","Galarian Slowking","Galarian Corsola","Galarian Zigzagoon","Galarian Linoone",
          "Galarian Darumaka","Galarian Darmanitan","Galarian Yaamask","Galarian Stunfisk",

          "Kleavor","Wyrdeer","Basculegion","Sneasler","Overqwil","Ursaluna","Enamorus","Hisuian Voltorb",
          "Hisuian Electrode","Hisuian Zorua","Hisuian Zoroark","Hisuian Braviary","Hisuian Growlithe",
          "Hisuian Arcanine","Hisuian Typhlosion","Hisuian Qwilfish","Hisuian Sneasel","Hisuian Samurott",
          "Hissuan Lilligant","Hisuian Sliggoo","Hisuian Goodra","Hisuian Avalugg","Hisuian Decidueye","Origin Dialga",
          "Origin Palkia",

          ]

slot1 = random.choice(pkmons)
slot2 = random.choice(pkmons)
slot3 = random.choice(pkmons)
slot4 = random.choice(pkmons)
slot5 = random.choice(pkmons)
slot6 = random.choice(pkmons)

print("1. {}\n2. {}\n3. {}\n4. {}\n5. {}\n6. {}".format(slot1,slot2,slot3,slot4,slot5,slot6))

